export const ALL_BLOGS_REQUEST  = "ALL_BLOGS_REQUEST";
export const ALL_BLOGS_FAILS  = "ALL_BLOGS_FAILS";
export const ALL_BLOGS_SUCCESS  = "ALL_BLOGS_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";