export const ALL_BOOKING_REQUEST = "ALL_BOOKING_REQUEST";
export const ALL_BOOKING_SUCCESS = "ALL_BOOKING_SUCCESS";
export const ALL_BOOKING_FAIL = "ALL_BOOKING_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";